name: Prepare deploy goerli
on:
  repository_dispatch:
    types: [trigger-deploy-goerli]

jobs:
  trigger-deploy-goerli:
    name: Get commits needed for subgraph deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.FRONTEND_COMMIT}}
          repository: JoinColony/colonyDapp
      - name: Get commit for network
        run: |
          echo "NETWORK_COMMIT=${git ls-tree HEAD:src/lib/ | grep colonyNetwork | awk '{ print $3 }'} >> $GITHUB_ENV"
      - name: Get commit for subgraph
        run: |
          echo "SUBGRAPH_COMMIT=${git ls-tree HEAD:src/lib/ | grep subgraph | awk '{ print $3 }'} >> $GITHUB_ENV"
      - name: Run build
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.CHEWIE_GITHUB_TOKEN }}
          event_type: repository_dispatch
          message: |
            {
              SUBGRAPH_COMMIT: $SUBGRAPH_COMMIT,
              NETWORK_COMMIT: $NETWORK_COMMIT
            }
