name: Prepare deploy goerli
on:
  repository_dispatch:
    types: [trigger-deploy-goerli]

jobs:
  trigger-deploy-goerli:
    name: Get commits needed for subgraph deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout subgraph repository
        uses: actions/checkout@v2
        with:
          repository: joinColony/subgraph
      - name: Install dependencies
        run: npm i
      - name: Checkout frontend repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.FRONTEND_COMMIT}}
          repository: JoinColony/colonyDapp
          path: ./colonyDapp
      - name: Get commit for network
        run: |
          cd colonyDapp
          git ls-tree HEAD:src/lib/ | grep colonyNetwork | awk '{ print $3 }'
          echo "NETWORK_COMMIT=`git ls-tree HEAD:src/lib/ | grep colonyNetwork | awk '{ print $3 }'` >> $GITHUB_ENV"
      - name: Get commit for subgraph
        run: |
          cd colonyDapp
          git ls-tree HEAD:src/lib/ | grep subgraph | awk '{ print $3 }'
          echo "SUBGRAPH_COMMIT=`git ls-tree HEAD:src/lib/ | grep subgraph | awk '{ print $3 }'` >> $GITHUB_ENV"
      - name: Trigger deploy with appropriate commits
        run: node ./scripts/trigger_deployment_action.js
        env:
          CHEWIE_GITHUB_TOKEN: ${{ secrets.CHEWIE_GITHUB_TOKEN }}
