name: Prepare deploy goerli
on:
  repository_dispatch:
    types: [trigger-deploy-xdai-qa]

jobs:
  trigger-deploy-xdai-qa:
    name: Get commits needed for subgraph deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout subgraph repository
        uses: actions/checkout@v2
        with:
          repository: joinColony/subgraph
      - name: npm upgrade
        run: npm i -g npm@8 --registry=https://registry.npmjs.org
        env:
          NPM_CONFIG_PREFIX: "~/.npm-global"
      - name: Install dependencies
        run: npm i
      - name: Checkout frontend repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.FRONTEND_COMMIT}}
          repository: JoinColony/colonyDapp
          path: ./colonyDapp
      - name: Trigger deploy with appropriate commits
        run: |
          NETWORK_COMMIT=`cd colonyDapp && git ls-tree HEAD:src/lib/ | grep colonyNetwork | awk '{ print $3 }'`
          SUBGRAPH_COMMIT=`cd colonyDapp && git ls-tree HEAD:src/lib/ | grep subgraph | awk '{ print $3 }'`
          NETWORK_COMMIT=$NETWORK_COMMIT SUBGRAPH_COMMIT=$SUBGRAPH_COMMIT EVENT_TYPE=deploy-xdai-qa node ./scripts/trigger_deployment_action.js
        env:
          CHEWIE_GITHUB_TOKEN: ${{ secrets.CHEWIE_GITHUB_TOKEN }}
